 + Bacillus anthracis str. A0465, unfinished sequence                           
=+ 0.856000                                                                     
 +--------------------------+ Bacillus anthracis str. A0389, unfinished sequence
                                                                                
 |---|--|---|--|---|--|---|--|                                                  
 0.000255007500101250150175002                                                  
 substitutions/site                                                             
                                                                                
