                                        +---------------+ Gorilla               
                                        |                                       
                          +-------------+ Homininae---------+ Pan               
                          |             +---------+ Hominini                    
           +--------------+ Hominidae             +---------+ Homo              
           |              |                                                     
 +---------+              +----------------------------+ Pongo                  
 |         |                                                                    
 |         +-------------------+ Hylobates                                      
 |                                                                              
=|                                                     +---------+ Macaca       
 |                                 +-------------------+                        
 |         +-----------------------+ Cercopithecinae   +---------+ Papio        
 |         |                       |                                            
 |         |                       +---------+ Cercopithecus                    
 +---------+ Cercopithecidae                                                    
           |    +---------+ Simias                                              
           +----+ Colobinae                                                     
                +------+ Colobus                                                
                                                                                
