Pandion	Buteo	Aquila	Haliaeetus	Milvus	Elanus	Sagittarius	Micrastur	Falco	Polyborus	Milvagus
1	3	3	3	3	3	1	3	3	3	3
Diomedea	Daption	Fregata	Phalacrocorax	Sula	Larus	Fratercula	Uria
2	2	2	2	2	2	3	3
Ticodendraceae	Betulaceae	Casuarinaceae	Rhoipteleaceae	Juglandaceae	Myricaceae
4	3	4	3	4	2
Gorilla	Pan	Homo	Pongo	Hylobates	Macaca	Papio	Cercopithecus	Simias	Colobus
56	60	60	55	30	65	65	45	25	22
Homo	Pan	Gorilla	Pongo	Hylobates	Cercopithecus	Macaca	Papio	Simias	Cebus
1	2	3	4	5	8	9	9	7	6
