 | Bacillus anthracis str. A0465, unfinished sequence                           
=| 0.856000                                                                     
 +--------------------------+ Bacillus anthracis str. A0389, unfinished sequence
                                                                                
 |---|--|---|--|---|--|---|--                                                   
 0.0.00.0000.0.000.00.00175                                                     
 substitutions/site                                                             
                                                                                
