 | Bacillus anthracis str. A0465, unfinished sequence                           
=| 0.856000                                                                     
 +--------------------------+ Bacillus anthracis str. A0389, unfinished sequence
                                                                                
 --|---|--|---|--|---|--|---|                                                   
 0.00175125.0010750005025e-11                                                   
 substitutions/site                                                             
                                                                                
