(Pandion,((Buteo,Aquila,Haliaeetus),(Milvus,Elanus)),Sagittarius,((Micrastur,Falco),(Polyborus,Milvagus)));
((Diomedea,Daption),(Fregata,Phalacrocorax,Sula),(Larus,(Fratercula,Uria)));
(((Ticodendraceae,Betulaceae),Casuarinaceae),(Rhoipteleaceae,Juglandaceae),Myricaceae);
((((Gorilla,(Pan,Homo)Hominini)Homininae,Pongo)Hominidae,Hylobates),(((Macaca,Papio),Cercopithecus)Cercopithecinae,(Simias,Colobus)Colobinae)Cercopithecidae);
(Homo,(Pan,(Gorilla,(Pongo,(Hylobates,(((Cercopithecus,(Macaca,Papio)),Simias),Cebus))))));
