Type:	Cladogram
#nodes:	18
#leaves:	11
#dichotomies:	5
#leaf labels:	11
#inner labels:	0
Type:	Cladogram
#nodes:	13
#leaves:	8
#dichotomies:	3
#leaf labels:	8
#inner labels:	0
Type:	Phylogram
#nodes:	10
#leaves:	6
#dichotomies:	3
#leaf labels:	6
#inner labels:	0
Type:	Phylogram
#nodes:	19
#leaves:	10
#dichotomies:	9
#leaf labels:	10
#inner labels:	6
Type:	Cladogram
#nodes:	19
#leaves:	10
#dichotomies:	9
#leaf labels:	10
#inner labels:	0
