 +-----------------+ Cebus                                                      
 |                                                                              
 |                                                         +-----+ Macaca       
 |                                             +-----------+                    
 |                             +-Cercopithecinae           +-----+ Papio        
=|                             |               |                                
 |                             |               +-----+ Cercopithecus            
 |                 +-Cercopithecidae                                            
 |                 |           |   +-----+ Simias                               
 |                 |           +-Colobinae                                      
 +-----------------+               +---+ Colobus                                
                   |                                                            
                   |           +------------+ Hylobates                         
                   |           |                                                
                   +-----------+         +-----------------+ Pongo              
                               |         |                                      
                               +-Hominidae        +---------+ Gorilla           
                                         |        |                             
                                         +-Homininae    +-----+ Pan             
                                                  +-Hominini                    
                                                        +-----+ Homo            
                                                                                
